services:
  api-gateway:
    build:
      context: ./
      dockerfile: ./api_gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./utils.py:/app/utils.py
    depends_on:
      - auth-service
      - currency-service
      - gacha-service
      - market-service
      - db-manager
    secrets:
      - certificate
      - key

  auth-service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"
    volumes:
      - ./utils.py:/app/utils.py
    depends_on:
      - db-manager
    secrets:
      - certificate
      - key

  gacha-service:
    build:
      context: ./
      dockerfile: ./gacha_service/Dockerfile
    container_name: gacha-service
    ports:
      - "8002:8002"
    volumes:
      - ./utils.py:/app/utils.py
    depends_on:
      - db-manager
    secrets:
      - certificate
      - key

  currency-service:
    build:
      context: ./
      dockerfile: ./currency_service/Dockerfile
    container_name: currency-service
    ports:
      - "8004:8004"
    volumes:
      - ./utils.py:/app/utils.py
      - ./img:/app/img
    depends_on:
      - db-manager
      - market-service
    secrets:
      - certificate
      - key

  market-service:
    build:
      context: ./
      dockerfile: ./market_service/Dockerfile
    container_name: market-service
    ports:
      - "8003:8003"
    volumes:
      - ./utils.py:/app/utils.py
    depends_on:
      - db-manager
    secrets:
      - certificate
      - key

  db-manager:
    build:
      context: ./
      dockerfile: ./db_manager/Dockerfile
    container_name: db-manager
    ports:
      - "8005:8005"
    volumes:
      - ./utils.py:/app/utils.py
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ase
    secrets:
      - certificate
      - key
#      - db_password

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ase
    volumes:
      - ./mysql-data:/var/lib/mysql

secrets:
  certificate:
    file: ./secrets/cert.pem
  key:
    file: ./secrets/key.pem
#  db_password:
#    file: ./secrets/mongo_password.txt
