version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ase
      MYSQL_USER: gachauser
      MYSQL_PASSWORD: gachapassword
    ports:
      - "3307:3306"  # Espone la porta di MySQL per connessioni esterne
    networks:
      - gacha-network

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=ase

  # Nginx Proxy per auth-service
  nginx-auth-proxy:
    image: nginx:latest
    volumes:
      - ./nginx_auth_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - gacha-network
    depends_on:
      - auth-service

  # Swagger UI per auth-service
  swagger-ui-auth:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /openAP/auth_service_openapi.yaml
    volumes:
      - ./openAP:/openAP
    ports:
      - "8082:8080"
    networks:
      - gacha-network
    depends_on:
      - nginx-auth-proxy

networks:
  gacha-network:

volumes:
  mysql_data:
