version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gachadb
      MYSQL_USER: gachauser
      MYSQL_PASSWORD: gachapassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gacha-network

  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    networks:
      - gacha-network
    depends_on:
      - auth-service
      - gacha-service
      - auction-service

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=gachadb

  gacha-service:
    build: ./gacha_service
    ports:
      - "8002:8002"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=gachadb

  auction-service:
    build: ./auction_service
    ports:
      - "8003:8003"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=gachadb

  # Swagger UI per auth_service
  swagger-ui-auth:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openAP/auth_service_openapi.yaml
    volumes:
      - ./openAP:/openAP
    networks:
      - gacha-network

  # Swagger UI per gacha_service
  swagger-ui-gacha:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    environment:
      SWAGGER_JSON: /openAP/gacha_service_openapi.yaml
    volumes:
      - ./openAP:/openAP
    networks:
      - gacha-network

  # Swagger UI per auction_service
  swagger-ui-auction:
    image: swaggerapi/swagger-ui
    ports:
      - "8083:8080"
    environment:
      SWAGGER_JSON: /openAP/auction_service_openapi.yaml
    volumes:
      - ./openAP:/openAP
    networks:
      - gacha-network

networks:
  gacha-network:

volumes:
  mysql_data:
