services:
  api-gateway:
    build:
      context: ./src
      dockerfile: ./api_gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./src/api_gateway:/app/
      - ./src/utils.py:/app/utils.py

    depends_on:
      - auth-service
      - currency-service
      - gacha-service
      - market-service
    networks:
      - gacha-network

  auth-service:
    build:
      context: ./src
      dockerfile: ./auth_service/Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"
    volumes:
      - ./src/auth_service:/app
      - ./src/utils.py:/app/utils.py
    networks:
      - gacha-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ase

  gacha-service:
    build:
      context: ./src
      dockerfile: ./gacha_service/Dockerfile
    container_name: gacha-service
    ports:
      - "8002:8002"
    volumes:
      - ./src/gacha_service:/app
      - ./src/utils.py:/app/utils.py
    networks:
      - gacha-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ase

  currency-service:
    build:
      context: ./src
      dockerfile: ./currency_service/Dockerfile
    container_name: currency-service
    ports:
      - "8004:8004"
    volumes:
      - ./src/currency_service:/app
      - ./src/utils.py:/app/utils.py
      - ./src/img:/app/img
    networks:
      - gacha-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ase

  market-service:
    build:
      context: ./src
      dockerfile: ./market_service/Dockerfile
    container_name: market-service
    ports:
      - "8003:8003"
    volumes:
      - ./src/market_service:/app
      - ./src/utils.py:/app/utils.py
    networks:
      - gacha-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ase

  db-manager:
    build:
      context: ./src
      dockerfile: ./db_manager/Dockerfile
    container_name: db-manager
    ports:
      - "8005:8005"
    volumes:
      - ./src/db_manager:/app
      - ./src/utils.py:/app/utils.py
    networks:
      - gacha-network
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=ase

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ase
    volumes:
      - ./src/mysql-data:/var/lib/mysql
    networks:
      - gacha-network

networks:
  gacha-network:
    driver: bridge #aaaaaaaaaa
