version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gachadb
      MYSQL_USER: gachauser
      MYSQL_PASSWORD: gachapassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gacha-network

  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    networks:
      - gacha-network
    depends_on:
      - auth-service
      - gacha-service
      - auction-service

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=gachadb

  gacha-service:
    build: ./gacha_service
    ports:
      - "8002:8002"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=gachadb

  auction-service:
    build: ./auction_service
    ports:
      - "8003:8003"
    networks:
      - gacha-network
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=gachauser
      - DATABASE_PASSWORD=gachapassword
      - DATABASE_NAME=gachadb

networks:
  gacha-network:

volumes:
  mysql_data:
