openapi: 3.0.3
info:
  title: Currency Service API
  description: |-
    This API is part of a microservices architecture and serves as the currency management service
    for the application. It provides operations for managing in-game currency and rolling gacha items.
    
    
    Some useful links:
    - [The Pokémon Gacha repository](https://github.com/ardiz99/TBAse)
    - [The source APIs definition for the Pokémon Gacha](https://github.com/ardiz99/TBAse/OpenAPI)
  version: 1.0.0
  x-microservice: currency-service
servers:
  - url: http://currency-service:8004
    description: Currency Service in Docker environment
  - url: http://127.0.0.1:8004
    description: Currency Service on local development
tags:
  - name: Currency Service
    description: API operations related to managing gacha in-game currency.
paths:
  /roll_info:
    get:
      tags:
        - Currency Service
      summary: Roll for a random item.
      description: Rolls the gacha system to retrieve an item based on rarity and updates the user's currency.
      responses:
        '200':
          description: Successfully rolled for an item.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  data:
                    type: object
                    description: Details of the selected gacha item.
                  message:
                    type: string
        '500':
          description: Insufficient funds or other server errors.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
  /roll_img:
    get:
      summary: Retrieve an image for a specific gacha item.
      tags:
        - Currency Service
      parameters:
        - name: url
          in: query
          required: true
          description: Path to the image file.
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the image.
          content:
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: Image not found.
  /buy_currency:
    put:
      summary: Purchase in-game currency.
      tags:
        - Currency Service
      description: Adds a specified quantity of currency to the user's account.
      parameters:
        - name: quantity
          in: query
          required: true
          description: Quantity of currency to add.
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Currency updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
        '400':
          description: Invalid quantity provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  message:
                    type: string
