openapi: 3.0.1
info:
  title: Authentication Service
  version: 1.0.0
  description: Gestisce la registrazione e l'autenticazione degli utenti per il gioco.

servers:
  - url: http://localhost:8081
    description: URL proxy per l'autenticazione tramite Nginx

paths:
  /register:
    post:
      summary: Registrazione nuovo utente
      description: Endpoint per registrare un nuovo utente.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                UserId:
                  type: string
                FirstName:
                  type: string
                LastName:
                  type: string
                Email:
                  type: string
                Password:
                  type: string
                CurrencyAmount:
                  type: number
                  format: float
      responses:
        '201':
          description: Utente registrato con successo.
        '400':
          description: Richiesta non valida

  /login:
    post:
      summary: Login e accesso token
      description: Endpoint per effettuare il login e ottenere un token JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Email:
                  type: string
                Password:
                  type: string
      responses:
        '200':
          description: Token di accesso recuperato con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token JWT per accedere agli endpoint protetti.
        '401':
          description: Non autorizzato

  /protected:
    get:
      summary: Accesso a risorsa protetta
      description: Endpoint per accedere alle risorse protette che richiedono un token JWT valido.
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: "Bearer <your_token>"
      responses:
        '200':
          description: Accesso consentito alla risorsa protetta.
        '401':
          description: Token non valido o scaduto
