FROM python:3.12-slim

WORKDIR /app

COPY ./currency_service/main*.py .
COPY ./currency_service/requirements.txt .
COPY ./secrets/cert.pem /run/secrets/certificate
COPY ./secrets/key.pem /run/secrets/key
COPY ../utils.py ./utils.py  
COPY ./img ./img

RUN pip install -r requirements.txt

EXPOSE 5002

ENV FLASK_APP=main_test
CMD ["flask", "run", "--host=0.0.0.0", "--port=5002", "--cert=/run/secrets/certificate", "--key=/run/secrets/key"]